=== OSGeo/PROJ/data/triangulation.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema for triangulation based transformation",
  "type": "object",
  "properties": {
    "file_type": {
      "type": "string",
      "enum": [
        "triangulation_file"
      ],
      "description": "File type. Always \"triangulation_file\""
    },
    "format_version": {
      "type": "string",
      "enum": [
        "1.0"
      ]
    },
    "name": {
      "type": "string",
      "description": "A brief descriptive name of the triangulation"
    },
    "version": {
      "type": "string",
      "description": "A string identifying the version of the triangulation. The format for specifying version will be defined by the agency responsible for the triangulation"
    },
    "publication_date": {
      "$ref": "#/definitions/datetime",
      "description": "The date on which this version of the triangulation was published (or possibly the date on which it takes effect?)"
    },
    "license": {
      "type": "string",
      "description": "License under which the file is published"
    },
    "description": {
      "type": "string",
      "description": "A text description of the file"
    },
    "authority": {
      "type": "object",
      "description": "Basic information about the agency responsible for the data set",
      "properties": {
        "name": {
          "type": "string",
          "description": "The name of the agency"
        },
        "url": {
          "type": "string",
          "description": "The url of the agency website",
          "format": "uri"
        },
        "address": {
          "type": "string",
          "description": "The postal address of the agency"
        },
        "email": {
          "type": "string",
          "description": "An email contact address for the agency",
          "format": "email"
        }
      },
      "required": [
        "name"
      ],
      "additionalProperties": false
    },
    "links": {
      "type": "array",
      "description": "Links to related information",
      "items": {
        "type": "object",
        "properties": {
          "href": {
            "type": "string",
            "description": "The URL holding the information",
            "format": "uri"
          },
          "rel": {
            "type": "string",
            "description": "The relationship to the dataset. Proposed relationships are:\n- \"about\": a web page for human consumption describing the model\n- \"source\": the authoritative source data from which the triangulation is built.\n- \"metadata\": ISO 19115 XML metadata regarding the triangulation."
          },
          "type": {
            "type": "string",
            "description": "MIME type"
          },
          "title": {
            "type": "string",
            "description": "Description of the link"
          }
        },
        "required": [
          "href"
        ],
        "additionalProperties": false
      }
    },
    "extent": {
      "$ref": "#/definitions/extent",
      "description": "Defines the region within which the triangulation is defined. This should be a bounding box defined as an array of [west,south,east,north] coordinate values in a unspecified geographic CRS. This bounding box should be seen as approximate, given that triangulation may be defined with projected coordinates, and also because some triangulations may not cover the whole bounding box."
    },
    "input_crs": {
      "$ref": "#/definitions/crs",
      "description": "String identifying the CRS of source coordinates in the vertices. Typically \"EPSG:XXXX\". If the transformation is for vertical component, this should be the code for a compound CRS (can be EPSG:XXXX+YYYY where XXXX is the code of the horizontal CRS and YYYY the code of the vertical CRS). For example, for the KKJ->ETRS89 transformation, this is EPSG:2393 (\"KKJ / Finland Uniform Coordinate System\"). The input coordinates are assumed to be passed in the \"normalized for visualisation\" / \"GIS friendly\" order, that is longitude, latitude for geographic coordinates and easting, northing for projected coordinates."
    },
    "output_crs": {
      "$ref": "#/definitions/crs",
      "description": "String identifying the CRS of target coordinates in the vertices. Typically \"EPSG:XXXX\". If the transformation is for vertical component, this should be the code for a compound CRS (can be EPSG:XXXX+YYYY where XXXX is the code of the horizontal CRS and YYYY the code of the vertical CRS). For example, for the KKJ->ETRS89 transformation, this is EPSG:3067 (\"ETRS89 / TM35FIN(E,N)\"). The output coordinates will be returned in the \"normalized for visualisation\" / \"GIS friendly\" order, that is easting, that is longitude, latitude for geographic coordinates and easting, northing for projected coordinates."
    },
    "transformed_components": {
      "type": "array",
      "description": "Specify which component of the coordinates are transformed. Either \"horizontal\", \"vertical\" or both",
      "minItems": 1,
      "maxItems": 2,
      "items": {
        "type": "string",
        "enum": [
          "horizontal",
          "vertical"
        ]
      }
    },
    "vertices_columns": {
      "type": "array",
      "description": "Specify the name of the columns of the rows in the \"vertices\" array. There must be exactly as many elements in \"vertices_columns\" as in a row of \"vertices\". The following names have a special meaning: \"source_x\", \"source_y\", \"target_x\", \"target_y\", \"source_z\", \"target_z\" and \"offset_z\".  \"source_x\" and \"source_y\" are compulsory. \"source_x\" is for the source longitude (in degree) or easting. \"source_y\" is for the source latitude (in degree) or northing.  \"target_x\" and \"target_y\" are compulsory when \"horizontal\" is specified in \"transformed_components\". (\"source_z\" and \"target_z\") or \"offset_z\" are compulsory when \"vertical\" is specified in \"transformed_components\".",
      "minItems": 3,
      "items": {
        "type": "string"
      }
    },
    "triangles_columns": {
      "type": "array",
      "description": "Specify the name of the columns of the rows in the \"triangles\" array. There must be exactly as many elements in \"triangles_columns\" as in a row of \"triangles\". The following names have a special meaning: \"idx_vertex1\", \"idx_vertex2\", \"idx_vertex3\". They are compulsory.",
      "minItems": 3,
      "items": {
        "type": "string"
      }
    },
    "vertices": {
      "type": "array",
      "description": "an array whose items are themselves arrays with as many columns as described in \"vertices_columns\"",
      "items": {
        "type": "array"
      }
    },
    "triangles": {
      "type": "array",
      "description": "an array whose items are themselves arrays with as many columns as described in \"triangles_columns\". The value of the \"idx_vertexN\" columns must be indices (between 0 and len(\"vertices\"-1) of items of the \"vertices\" array",
      "items": {
        "type": "array"
      }
    }
  },
  "required": [
    "file_type",
    "format_version",
    "transformed_components",
    "vertices_columns",
    "triangles_columns",
    "vertices",
    "triangles"
  ],
  "additionalProperties": false,
  "definitions": {
    "crs": {
      "type": "string"
    },
    "datetime": {
      "type": "string",
      "format": "date-time",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
    },
    "extent": {
      "type": "object",
      "properties": {
        "type": {
          "type": "string",
          "enum": [
            "bbox"
          ]
        },
        "name" : {
          "type": "string",
          "description": "Name of the extent (e.g. \"Finland - mainland south of 66Â°N\")"
        },
        "parameters": {
          "type": "object",
          "properties": {
            "bbox": {
              "type": "array",
              "minItems": 4,
              "maxItems": 4,
              "items": {
                "type": "number"
              }
            }
          }
        }
      },
      "required": [
        "type",
        "parameters"
      ],
      "additionalProperties": false
    }
  }
}

=== OSGeo/PROJ/data/tests/tinshift_simplified_etrs89_ngo48.json
{"authority":{"address":"Postboks 600 Sentrum, NO-3507 Hoenefoss, NORWAY","email":"post@kartverket.no","name":"Kartverket","url":"https://www.kartverket.no/til-lands/posisjon/transformere-koordinater"},"description":"Triangulation to transform coordinates from EUREF89 (EPSG:4258) to NGO1948 (EPSG:4273), with longitude/latitude order.","extent":{"name":"Norway - onshore","parameters":{"bbox":[4.68,57.93,31.22,71.21]},"type":"bbox"},"file_type":"triangulation_file","format_version":"1.0","input_crs":"EPSG:4258","license":"Creative Commons Attribution 4.0 International","name":"tinshift_simplified_etrs89_ngo48.json","output_crs":"EPSG:4273","publication_date":"2021-03-03T10:08:55.88Z","transformed_components":["horizontal"],"triangles":[[20,19,5],[20,28,19],[5,26,20],[28,36,19],[25,24,5],[5,24,26],[20,32,28],[28,13,36],[25,5,19],[2,25,19],[15,13,28],[36,2,19],[13,2,36],[32,15,28],[26,21,20],[20,0,32],[23,21,26],[24,23,26],[22,0,20],[15,33,13],[13,33,2],[8,9,21],[21,22,20],[18,4,32],[32,4,15],[15,27,33],[9,22,21],[34,27,15],[10,1,0],[0,18,32],[30,18,0],[16,34,12],[4,34,15],[6,8,23],[23,8,21],[1,30,0],[12,34,4],[25,6,24],[24,6,23],[34,29,27],[27,29,33],[33,29,2],[22,10,0],[17,14,30],[3,10,22],[34,35,29],[16,35,34],[12,4,31],[31,4,18],[17,30,1],[30,14,18],[14,31,18],[12,31,16],[10,17,1],[14,17,31],[8,3,9],[9,3,22],[11,3,8],[6,7,8],[7,11,8]],"triangles_columns":["idx_vertex1","idx_vertex2","idx_vertex3"],"version":"1.2","vertices":[[10.5680110964,59.8287112888,10.572807685,59.8279216141],[10.5593886459,59.8114663879,10.5641821497,59.8106753272],[10.5708852465,59.9925378474,10.5757047163,59.9917649517],[10.7559654748,59.8315857188,10.760777932,59.8307897136],[10.5048780867,59.8809865177,10.5096755401,59.8802032878],[10.6320197818,59.9413249493,10.6368374086,59.9405449096],[10.7333021491,59.9693392211,10.7381321725,59.9685586306],[10.8087251886,59.9499447253,10.8135588647,59.9491594199],[10.7376120371,59.9025359576,10.7424329797,59.9017479716],[10.6794285495,59.8357326941,10.684235043,59.8349398303],[10.608315398,59.7797041504,10.6131080723,59.7789080207],[10.8420674345,59.8811435278,10.8468944229,59.8803495769],[10.4625380162,59.8877584196,10.467334834,59.886978296],[10.5369555492,59.9572147837,10.5417672219,59.9564392056],[10.4823826917,59.8323587006,10.4871729727,59.8315726135],[10.5220720426,59.9332358009,10.5268798281,59.9324585819],[10.4608842933,59.9166985713,10.4656842539,59.9159215302],[10.472460354,59.8240900858,10.4772485513,59.8233036322],[10.5121497049,59.8505496531,10.5169447933,59.8497639937],[10.5981432986,59.9464655845,10.6029591477,59.9456872117],[10.619641697,59.8885852811,10.6244508715,59.8877998579],[10.6709071086,59.8488959302,10.6757147562,59.8481047244],[10.6411400954,59.8075528563,10.645939402,59.8067584485],[10.7056352907,59.9216597402,10.7104562136,59.9208749159],[10.6725608315,59.9696177059,10.6773855287,59.9688392702],[10.6477549872,59.9911161043,10.6525810632,59.9903408572],[10.6692533856,59.929928355,10.674072379,59.9291457621],[10.4989199213,59.9481193075,10.5037280769,59.9473441284],[10.5634151165,59.9166985713,10.5682239472,59.9159180194],[10.4774215228,59.9514267534,10.4822286336,59.9506525753],[10.5138034278,59.8290512547,10.5185960158,59.8282636568],[10.4641917392,59.8522033761,10.4689830651,59.8514198475],[10.5386092722,59.8869315581,10.543411201,59.8861484358],[10.5187645967,59.9630028141,10.5235757746,59.9622283914],[10.4840364147,59.9150448484,10.4888385775,59.914266783],[10.4643295436,59.9375502427,10.4691321615,59.9367749937],[10.5677670658,59.9652883024,10.5725818874,59.9645124836]],"vertices_columns":["source_x","source_y","target_x","target_y"]}

=== OSGeo/PROJ/data/tests/tinshift_simplified_n60_n2000.json
{
  "file_type": "triangulation_file",
  "format_version": "1.0",
  "name": "Name",
  "version": "Version",
  "publication_date": "2018-07-01T00:00:00Z",
  "license": "Creative Commons Attribution 4.0 International",
  "description": "Test triangulation",
  "authority": {
    "name": "Authority name",
    "url": "http://example.com",
    "address": "Adress",
    "email": "test@example.com"
  },
  "links": [
    {
      "href": "https://example.com/about.html",
      "rel": "about",
      "type": "text/html",
      "title": "About"
    },
    {
      "href": "https://example.com/download",
      "rel": "source",
      "type": "application/zip",
      "title": "Authoritative source"
    },
    {
      "href": "https://creativecommons.org/licenses/by/4.0/",
      "rel": "license",
      "type": "text/html",
      "title": "Creative Commons Attribution 4.0 International license"
    },
    {
      "href": "https://example.com/metadata.xml",
      "rel": "metadata",
      "type": "application/xml",
      "title": " ISO 19115 XML encoded metadata regarding the tirangulation"
    }
  ],
  "input_crs": "EPSG:2393+5717",
  "output_crs": "EPSG:2393+5941",
  "transformed_components": [ "vertical" ],
  "vertices_columns": [ "source_x", "source_y", "source_z", "target_z" ],
  "triangles_columns": [ "idx_vertex1", "idx_vertex2", "idx_vertex3" ],
  "vertices": [ [3188607.0, 6688748.0, 23.123, 23.4133],
                [3184981.0, 6725255.0, 8.044, 8.34499],
                [3220912.0, 6699508.0, 1.724, 2.0101] ],
  "triangles": [ [0, 1, 2] ]
}
